# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
