# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_src',
            field=models.ImageField(default='usr_pic_src/<django.db.models.fields.DateTimeField>.jpg', upload_to='backend/posts/picture/'),
        ),
    ]
