# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
